-- CRM Module Migration
-- Creates CRM tables: contacts, pipelines, pipeline_stages, deals, activities, contact_lists, contact_list_memberships

CREATE TABLE wehoware_crm_contacts (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  client_id VARCHAR(36) NOT NULL,
  type ENUM('Lead','Customer') NOT NULL DEFAULT 'Lead',
  status ENUM('New','Contacted','Qualified','Unqualified','Converted') NOT NULL DEFAULT 'New',
  source ENUM('Website','SocialMedia','FormBuilder','Appointment','PhoneCall','Email','Manual','Referral','Event','Other') NOT NULL DEFAULT 'Manual',
  first_name VARCHAR(100) NULL,
  last_name VARCHAR(100) NULL,
  email VARCHAR(255) NULL,
  phone VARCHAR(50) NULL,
  company VARCHAR(255) NULL,
  job_title VARCHAR(255) NULL,
  avatar_url VARCHAR(500) NULL,
  website VARCHAR(500) NULL,
  linkedin_url VARCHAR(500) NULL,
  social_profiles JSON NULL,
  social_platform VARCHAR(50) NULL,
  social_inbox_conversation_id VARCHAR(36) NULL,
  form_submission_id VARCHAR(36) NULL,
  appointment_id VARCHAR(36) NULL,
  accounting_customer_id VARCHAR(36) NULL,
  inquiry_subject VARCHAR(500) NULL,
  inquiry_message TEXT NULL,
  inquiry_service_id VARCHAR(36) NULL,
  notes TEXT NULL,
  tags JSON NULL,
  custom_fields JSON NULL,
  assigned_to VARCHAR(36) NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  created_by VARCHAR(36) NULL,
  updated_by VARCHAR(36) NULL,
  UNIQUE KEY wehoware_crm_contacts_client_id_email_key (client_id, email),
  INDEX wehoware_crm_contacts_client_id_idx (client_id),
  INDEX wehoware_crm_contacts_type_idx (type),
  INDEX wehoware_crm_contacts_status_idx (status),
  INDEX wehoware_crm_contacts_source_idx (source),
  INDEX wehoware_crm_contacts_active_idx (active),
  INDEX wehoware_crm_contacts_assigned_to_fkey (assigned_to),
  INDEX wehoware_crm_contacts_created_by_fkey (created_by),
  INDEX wehoware_crm_contacts_updated_by_fkey (updated_by),
  INDEX wehoware_crm_contacts_social_inbox_conv_fkey (social_inbox_conversation_id),
  CONSTRAINT wehoware_crm_contacts_client_id_fkey FOREIGN KEY (client_id) REFERENCES wehoware_clients(id) ON DELETE CASCADE,
  CONSTRAINT wehoware_crm_contacts_created_by_fkey FOREIGN KEY (created_by) REFERENCES wehoware_profiles(id),
  CONSTRAINT wehoware_crm_contacts_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES wehoware_profiles(id),
  CONSTRAINT wehoware_crm_contacts_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES wehoware_profiles(id),
  CONSTRAINT wehoware_crm_contacts_social_inbox_conv_fkey FOREIGN KEY (social_inbox_conversation_id) REFERENCES wehoware_social_inbox_conversations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE wehoware_crm_pipelines (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  client_id VARCHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  created_by VARCHAR(36) NULL,
  updated_by VARCHAR(36) NULL,
  INDEX wehoware_crm_pipelines_client_id_idx (client_id),
  INDEX wehoware_crm_pipelines_active_idx (active),
  INDEX wehoware_crm_pipelines_created_by_fkey (created_by),
  INDEX wehoware_crm_pipelines_updated_by_fkey (updated_by),
  CONSTRAINT wehoware_crm_pipelines_client_id_fkey FOREIGN KEY (client_id) REFERENCES wehoware_clients(id) ON DELETE CASCADE,
  CONSTRAINT wehoware_crm_pipelines_created_by_fkey FOREIGN KEY (created_by) REFERENCES wehoware_profiles(id),
  CONSTRAINT wehoware_crm_pipelines_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES wehoware_profiles(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE wehoware_crm_pipeline_stages (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  pipeline_id VARCHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  stage_type ENUM('Lead','Qualified','Proposal','Negotiation','Won','Lost','Custom') NOT NULL DEFAULT 'Custom',
  display_order INT NOT NULL DEFAULT 0,
  color VARCHAR(50) NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  created_by VARCHAR(36) NULL,
  updated_by VARCHAR(36) NULL,
  INDEX wehoware_crm_pipeline_stages_pipeline_id_idx (pipeline_id),
  INDEX wehoware_crm_pipeline_stages_active_idx (active),
  INDEX wehoware_crm_pipeline_stages_display_order_idx (display_order),
  INDEX wehoware_crm_pipeline_stages_created_by_fkey (created_by),
  INDEX wehoware_crm_pipeline_stages_updated_by_fkey (updated_by),
  CONSTRAINT wehoware_crm_pipeline_stages_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES wehoware_crm_pipelines(id) ON DELETE CASCADE,
  CONSTRAINT wehoware_crm_pipeline_stages_created_by_fkey FOREIGN KEY (created_by) REFERENCES wehoware_profiles(id),
  CONSTRAINT wehoware_crm_pipeline_stages_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES wehoware_profiles(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE wehoware_crm_deals (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  client_id VARCHAR(36) NOT NULL,
  pipeline_id VARCHAR(36) NOT NULL,
  stage_id VARCHAR(36) NOT NULL,
  contact_id VARCHAR(36) NULL,
  title VARCHAR(500) NOT NULL,
  value DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  currency VARCHAR(10) NOT NULL DEFAULT 'CAD',
  status ENUM('Open','Won','Lost') NOT NULL DEFAULT 'Open',
  expected_close_date DATE NULL,
  closed_at DATETIME(3) NULL,
  closed_reason VARCHAR(255) NULL,
  notes TEXT NULL,
  tags JSON NULL,
  assigned_to VARCHAR(36) NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  created_by VARCHAR(36) NULL,
  updated_by VARCHAR(36) NULL,
  INDEX wehoware_crm_deals_client_id_idx (client_id),
  INDEX wehoware_crm_deals_pipeline_id_idx (pipeline_id),
  INDEX wehoware_crm_deals_stage_id_idx (stage_id),
  INDEX wehoware_crm_deals_contact_id_idx (contact_id),
  INDEX wehoware_crm_deals_status_idx (status),
  INDEX wehoware_crm_deals_active_idx (active),
  INDEX wehoware_crm_deals_assigned_to_fkey (assigned_to),
  INDEX wehoware_crm_deals_created_by_fkey (created_by),
  INDEX wehoware_crm_deals_updated_by_fkey (updated_by),
  CONSTRAINT wehoware_crm_deals_client_id_fkey FOREIGN KEY (client_id) REFERENCES wehoware_clients(id) ON DELETE CASCADE,
  CONSTRAINT wehoware_crm_deals_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES wehoware_crm_pipelines(id) ON DELETE CASCADE,
  CONSTRAINT wehoware_crm_deals_stage_id_fkey FOREIGN KEY (stage_id) REFERENCES wehoware_crm_pipeline_stages(id),
  CONSTRAINT wehoware_crm_deals_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES wehoware_crm_contacts(id) ON DELETE SET NULL,
  CONSTRAINT wehoware_crm_deals_created_by_fkey FOREIGN KEY (created_by) REFERENCES wehoware_profiles(id),
  CONSTRAINT wehoware_crm_deals_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES wehoware_profiles(id),
  CONSTRAINT wehoware_crm_deals_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES wehoware_profiles(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE wehoware_crm_activities (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  client_id VARCHAR(36) NOT NULL,
  contact_id VARCHAR(36) NULL,
  deal_id VARCHAR(36) NULL,
  type ENUM('Call','Email','Meeting','Note','Task','SocialMessage','FormBuilderSubmission','AppointmentBooked') NOT NULL,
  direction ENUM('Inbound','Outbound','Internal') NOT NULL DEFAULT 'Internal',
  title VARCHAR(500) NOT NULL,
  description TEXT NULL,
  scheduled_at DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  duration_minutes INT NULL,
  metadata JSON NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  created_by VARCHAR(36) NULL,
  updated_by VARCHAR(36) NULL,
  INDEX wehoware_crm_activities_client_id_idx (client_id),
  INDEX wehoware_crm_activities_contact_id_idx (contact_id),
  INDEX wehoware_crm_activities_deal_id_idx (deal_id),
  INDEX wehoware_crm_activities_type_idx (type),
  INDEX wehoware_crm_activities_direction_idx (direction),
  INDEX wehoware_crm_activities_scheduled_at_idx (scheduled_at),
  INDEX wehoware_crm_activities_completed_at_idx (completed_at),
  INDEX wehoware_crm_activities_active_idx (active),
  INDEX wehoware_crm_activities_created_by_fkey (created_by),
  INDEX wehoware_crm_activities_updated_by_fkey (updated_by),
  CONSTRAINT wehoware_crm_activities_client_id_fkey FOREIGN KEY (client_id) REFERENCES wehoware_clients(id) ON DELETE CASCADE,
  CONSTRAINT wehoware_crm_activities_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES wehoware_crm_contacts(id) ON DELETE CASCADE,
  CONSTRAINT wehoware_crm_activities_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES wehoware_crm_deals(id) ON DELETE SET NULL,
  CONSTRAINT wehoware_crm_activities_created_by_fkey FOREIGN KEY (created_by) REFERENCES wehoware_profiles(id),
  CONSTRAINT wehoware_crm_activities_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES wehoware_profiles(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE wehoware_crm_contact_lists (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  client_id VARCHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  filters JSON NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  created_by VARCHAR(36) NULL,
  updated_by VARCHAR(36) NULL,
  INDEX wehoware_crm_contact_lists_client_id_idx (client_id),
  INDEX wehoware_crm_contact_lists_active_idx (active),
  INDEX wehoware_crm_contact_lists_created_by_fkey (created_by),
  INDEX wehoware_crm_contact_lists_updated_by_fkey (updated_by),
  CONSTRAINT wehoware_crm_contact_lists_client_id_fkey FOREIGN KEY (client_id) REFERENCES wehoware_clients(id) ON DELETE CASCADE,
  CONSTRAINT wehoware_crm_contact_lists_created_by_fkey FOREIGN KEY (created_by) REFERENCES wehoware_profiles(id),
  CONSTRAINT wehoware_crm_contact_lists_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES wehoware_profiles(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE wehoware_crm_contact_list_memberships (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  list_id VARCHAR(36) NOT NULL,
  contact_id VARCHAR(36) NOT NULL,
  client_id VARCHAR(36) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY wehoware_crm_contact_list_memberships_list_id_contact_id_key (list_id, contact_id),
  INDEX wehoware_crm_contact_list_memberships_list_id_idx (list_id),
  INDEX wehoware_crm_contact_list_memberships_contact_id_idx (contact_id),
  INDEX wehoware_crm_contact_list_memberships_client_id_idx (client_id),
  CONSTRAINT wehoware_crm_contact_list_memberships_list_id_fkey FOREIGN KEY (list_id) REFERENCES wehoware_crm_contact_lists(id) ON DELETE CASCADE,
  CONSTRAINT wehoware_crm_contact_list_memberships_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES wehoware_crm_contacts(id) ON DELETE CASCADE,
  CONSTRAINT wehoware_crm_contact_list_memberships_client_id_fkey FOREIGN KEY (client_id) REFERENCES wehoware_clients(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
